[package]
name = "ethereum_sample"
version = "0.1.0"
edition = "2024"

[dependencies]
ethers = { version = "2.0.14", features = ["solc"] }
serde_json = "1.0.140"
tokio = { version = "1.44.1", features = ["full"] }
